name: proyecto-trazabilidad
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/backend
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      #- GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      #- GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - 3000:3000

  frontend:
    image: frontend
    container_name: frontend
    command: sh -c "npm install && npm start"
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/frontend
    ports:
      - 4200:4200

  database:
    image: database
    container_name: database
    build:
      context: ./database
    volumes:
      - ./database/scripts/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - 5436:5432
